### ISSUE TITLE
Demo has not been working properly for PC

### ISSUE THREAD

**Issue by utopictown** [ikarosu/vue-datepicker-mobile#1]
Please provide the proper demo for pc. Or is this really specific for mobile?

**Comment by ikarosu** [comment]
If you preview from PC browser, you need used development mode(F12) and toggle device toolbar(Ctrl + Shift + M).

**Comment by utopictown** [comment]
> If you preview from PC browser, you need used development mode(F12) and toggle device toolbar(Ctrl + Shift + M).

i know. so this is really for mobile only?

**Comment by ikarosu** [comment]
It's compatible PC now

**Comment by utopictown** [comment]
awesome!!
