### ISSUE TITLE
能否增加设置默认选中日期范围的功能？

### ISSUE THREAD

**Issue by rason560** [ikarosu/vue-datepicker-mobile#2]
谢谢作者分享了这么一个很适用于H5酒店预订业务的日历的插件。发现好像不能设置初始的选中的日期范围。可否增加这么一个prop接收这个设置？

**Comment by ikarosu** [comment]
感谢建议。

**Comment by readygosports** [comment]
> 谢谢作者分享了这么一个很适用于H5酒店预订业务的日历的插件。发现好像不能设置初始的选中的日期范围。可否增加这么一个prop接收这个设置？

写了个方法设置单个日期的，日期范围应该也差不多
setDefault(date) {
        this.reset()
        const defaultDate = new Date(date)
        var year = defaultDate.getFullYear()
        var month = defaultDate.getMonth() + 1
        var day = defaultDate.getDate()
        this.months.forEach(item => {
          if (item.year == year && item.month == month) {
            item.days.forEach(_day => {
              console.log(_day)
              if (_day.day == day) {
                this.$set(_day, 'begin', true)
              }
            })
          }
        })
      },
      reset() {
        this.months.forEach(item => {
            item.days.forEach(_day => {
                this.$set(_day, 'begin', false)
            })
        })
      },

**Comment by ikarosu** [comment]
> > 谢谢作者分享了这么一个很适用于H5酒店预订业务的日历的插件。发现好像不能设置初始的选中的日期范围。可否增加这么一个prop接收这个设置？
> 
> 写了个方法设置单个日期的，日期范围应该也差不多
> setDefault(date) {
> this.reset()
> const defaultDate = new Date(date)
> var year = defaultDate.getFullYear()
> var month = defaultDate.getMonth() + 1
> var day = defaultDate.getDate()
> this.months.forEach(item => {
> if (item.year == year && item.month == month) {
> item.days.forEach(_day => {
> console.log(_day)
> if (_day.day == day) {
> this.$set(_day, 'begin', true)
> }
> })
> }
> })
> },
> reset() {
> this.months.forEach(item => {
> item.days.forEach(_day => {
> this.$set(_day, 'begin', false)
> })
> })
> },

如果你测试通过的话，可以 Pull requests。
该版本我暂时没有精力维护， 过段时间后可能会重构一个版本。
谢谢

**Comment by ikarosu** [comment]
重构的v2版本加入了该功能，通过传入selected这个props来设置勾选
